# Generated by Django 6.0.5 on 2026-05-11 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('damage', 'Physical Damage'), ('functional', 'Functional Issue'), ('replaced_part', 'Replaced Part')], max_length=20)),
                ('default_deduction_pct', models.PositiveIntegerField(help_text='Fallback % deducted from base_value_ngn when no per-model DefectPricing row exists. Multiplicative stacking: final = base × ∏(1 − pct/100).')),
                ('applies_to_view', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('both', 'Both')], default='both', help_text='Controls which phone face shows the damage overlay in the UI.', max_length=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IphoneSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'iPhone Series',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IphoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(unique=True)),
                ('variant_type', models.CharField(choices=[('standard', 'Standard'), ('s', 'S'), ('s-plus', 'S Plus'), ('mini', 'Mini'), ('plus', 'Plus'), ('pro', 'Pro'), ('max', 'Max'), ('air', 'Air'), ('xr', 'XR')], max_length=10)),
                ('order', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.iphoneseries')),
            ],
            options={
                'ordering': ['series__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StorageVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(choices=[('32GB', '32 GB'), ('64GB', '64 GB'), ('128GB', '128 GB'), ('256GB', '256 GB'), ('512GB', '512 GB'), ('1TB', '1 TB'), ('2TB', '2 TB')], max_length=10)),
                ('swap_in_value_ngn', models.PositiveIntegerField(help_text='What the shop pays when accepting this used phone (NGN). Update as market rates shift.')),
                ('uk_end_user_price_ngn', models.PositiveIntegerField(help_text='UK-condition end-user market price (NGN). Used as the swap-to price in estimates.')),
                ('uk_reseller_price_ngn', models.PositiveIntegerField(blank=True, help_text='UK-condition reseller price (NGN).', null=True)),
                ('ng_end_user_price_ngn', models.PositiveIntegerField(blank=True, help_text='Nigerian-used end-user price after shop refurbishment (NGN).', null=True)),
                ('ng_reseller_price_ngn', models.PositiveIntegerField(blank=True, help_text='Nigerian-used reseller price (NGN).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_variants', to='core.iphonemodel')),
            ],
            options={
                'ordering': ['model__order', 'capacity'],
                'unique_together': {('model', 'capacity')},
            },
        ),
        migrations.CreateModel(
            name='SwapEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('from_base_value_ngn', models.PositiveIntegerField(help_text='Snapshot of from_storage.swap_in_value_ngn at estimate time.')),
                ('from_value_ngn', models.PositiveIntegerField(help_text='Trade-in value after all deductions applied.')),
                ('total_repair_cost_ngn', models.PositiveIntegerField(default=0, help_text='Sum of repair_cost_ngn for all declared defects on this model.')),
                ('to_value_ngn', models.PositiveIntegerField(help_text='Snapshot of to_storage.uk_end_user_price_ngn at estimate time.')),
                ('service_fee_ngn', models.PositiveIntegerField(help_text='Flat service charge at time of estimate (from settings.SWAP_SERVICE_FEE_NGN).')),
                ('net_amount_ngn', models.IntegerField(help_text='Positive = customer pays; negative = customer receives cashback.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defects', models.ManyToManyField(blank=True, to='core.defecttype')),
                ('from_storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swap_from', to='core.storagevariant')),
                ('to_storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swap_to', to='core.storagevariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefectPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_pct', models.PositiveIntegerField(help_text="% deducted from this model's base_value_ngn for this defect.")),
                ('repair_cost_ngn', models.PositiveIntegerField(help_text='Cost (NGN) to repair or replace this part on this model. Added on top of the swap difference — update whenever parts/labour prices change.')),
                ('is_active', models.BooleanField(default=True)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='core.defecttype')),
                ('iphone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_pricing', to='core.iphonemodel')),
            ],
            options={
                'verbose_name': 'Defect Pricing',
                'verbose_name_plural': 'Defect Pricing',
                'ordering': ['iphone_model__series__order', 'iphone_model__order', 'defect__order'],
                'unique_together': {('defect', 'iphone_model')},
            },
        ),
    ]
