# Generated by Django 6.0.5 on 2026-05-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectpricing',
            name='deduction_pct',
            field=models.PositiveIntegerField(help_text="% deducted from this model's base_value_ngn for this defect."),
        ),
        migrations.AlterField(
            model_name='defecttype',
            name='default_deduction_pct',
            field=models.PositiveIntegerField(help_text='Fallback % deducted from base_value_ngn when no per-model DefectPricing row exists. Multiplicative stacking: final = base × ∏(1 − pct/100).'),
        ),
    ]
